// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pkg/protocol/netstruct/proto/ice_turn.proto

package netstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ICE candidate for P2P NAT traversal
type ICECandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetMac     string                 `protobuf:"bytes,1,opt,name=target_mac,json=targetMac,proto3" json:"target_mac,omitempty"`
	Candidate     string                 `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string                 `protobuf:"bytes,3,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex uint32                 `protobuf:"varint,4,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICECandidate) Reset() {
	*x = ICECandidate{}
	mi := &file_pkg_protocol_netstruct_proto_ice_turn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidate) ProtoMessage() {}

func (x *ICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_ice_turn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidate.ProtoReflect.Descriptor instead.
func (*ICECandidate) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDescGZIP(), []int{0}
}

func (x *ICECandidate) GetTargetMac() string {
	if x != nil {
		return x.TargetMac
	}
	return ""
}

func (x *ICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *ICECandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *ICECandidate) GetSdpMlineIndex() uint32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

// TURN credentials for NAT traversal
type TURNCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ttl           uint32                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Uris          []string               `protobuf:"bytes,4,rep,name=uris,proto3" json:"uris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TURNCredentials) Reset() {
	*x = TURNCredentials{}
	mi := &file_pkg_protocol_netstruct_proto_ice_turn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TURNCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TURNCredentials) ProtoMessage() {}

func (x *TURNCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_ice_turn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TURNCredentials.ProtoReflect.Descriptor instead.
func (*TURNCredentials) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDescGZIP(), []int{1}
}

func (x *TURNCredentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TURNCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *TURNCredentials) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *TURNCredentials) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

var File_pkg_protocol_netstruct_proto_ice_turn_proto protoreflect.FileDescriptor

const file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDesc = "" +
	"\n" +
	"+pkg/protocol/netstruct/proto/ice_turn.proto\x12\tnetstruct\"\x8c\x01\n" +
	"\fICECandidate\x12\x1d\n" +
	"\n" +
	"target_mac\x18\x01 \x01(\tR\ttargetMac\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x03 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x04 \x01(\rR\rsdpMlineIndex\"o\n" +
	"\x0fTURNCredentials\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x12\x12\n" +
	"\x04uris\x18\x04 \x03(\tR\x04urisB\"Z n2n-go/pkg/protocol/netstruct/pbb\x06proto3"

var (
	file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDescOnce sync.Once
	file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDescData []byte
)

func file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDescGZIP() []byte {
	file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDesc), len(file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDesc)))
	})
	return file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDescData
}

var file_pkg_protocol_netstruct_proto_ice_turn_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protocol_netstruct_proto_ice_turn_proto_goTypes = []any{
	(*ICECandidate)(nil),    // 0: netstruct.ICECandidate
	(*TURNCredentials)(nil), // 1: netstruct.TURNCredentials
}
var file_pkg_protocol_netstruct_proto_ice_turn_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protocol_netstruct_proto_ice_turn_proto_init() }
func file_pkg_protocol_netstruct_proto_ice_turn_proto_init() {
	if File_pkg_protocol_netstruct_proto_ice_turn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDesc), len(file_pkg_protocol_netstruct_proto_ice_turn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_netstruct_proto_ice_turn_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_netstruct_proto_ice_turn_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_netstruct_proto_ice_turn_proto_msgTypes,
	}.Build()
	File_pkg_protocol_netstruct_proto_ice_turn_proto = out.File
	file_pkg_protocol_netstruct_proto_ice_turn_proto_goTypes = nil
	file_pkg_protocol_netstruct_proto_ice_turn_proto_depIdxs = nil
}
