// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pkg/protocol/netstruct/proto/leasesinfos.proto

package netstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对应 Go 中的 LeaseEdgeInfos
type IppoolLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	ExpiryNs      int64                  `protobuf:"varint,3,opt,name=expiry_ns,json=expiryNs,proto3" json:"expiry_ns,omitempty"`
	Sticky        bool                   `protobuf:"varint,4,opt,name=sticky,proto3" json:"sticky,omitempty"`
	LastRenewNs   int64                  `protobuf:"varint,5,opt,name=last_renew_ns,json=lastRenewNs,proto3" json:"last_renew_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IppoolLease) Reset() {
	*x = IppoolLease{}
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IppoolLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IppoolLease) ProtoMessage() {}

func (x *IppoolLease) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IppoolLease.ProtoReflect.Descriptor instead.
func (*IppoolLease) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescGZIP(), []int{0}
}

func (x *IppoolLease) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *IppoolLease) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *IppoolLease) GetExpiryNs() int64 {
	if x != nil {
		return x.ExpiryNs
	}
	return 0
}

func (x *IppoolLease) GetSticky() bool {
	if x != nil {
		return x.Sticky
	}
	return false
}

func (x *IppoolLease) GetLastRenewNs() int64 {
	if x != nil {
		return x.LastRenewNs
	}
	return 0
}

type LeaseEdgeInfos struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EdgeId                string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	IsRegistered          bool                   `protobuf:"varint,2,opt,name=is_registered,json=isRegistered,proto3" json:"is_registered,omitempty"`
	TimeSinceLastUpdateNs int64                  `protobuf:"varint,3,opt,name=time_since_last_update_ns,json=timeSinceLastUpdateNs,proto3" json:"time_since_last_update_ns,omitempty"`
	VirtualIp             []byte                 `protobuf:"bytes,4,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LeaseEdgeInfos) Reset() {
	*x = LeaseEdgeInfos{}
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseEdgeInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseEdgeInfos) ProtoMessage() {}

func (x *LeaseEdgeInfos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseEdgeInfos.ProtoReflect.Descriptor instead.
func (*LeaseEdgeInfos) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescGZIP(), []int{1}
}

func (x *LeaseEdgeInfos) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *LeaseEdgeInfos) GetIsRegistered() bool {
	if x != nil {
		return x.IsRegistered
	}
	return false
}

func (x *LeaseEdgeInfos) GetTimeSinceLastUpdateNs() int64 {
	if x != nil {
		return x.TimeSinceLastUpdateNs
	}
	return 0
}

func (x *LeaseEdgeInfos) GetVirtualIp() []byte {
	if x != nil {
		return x.VirtualIp
	}
	return nil
}

type LeaseWithEdgeInfos struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Lease          *IppoolLease           `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	LeaseEdgeInfos *LeaseEdgeInfos        `protobuf:"bytes,2,opt,name=lease_edge_infos,json=leaseEdgeInfos,proto3" json:"lease_edge_infos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseWithEdgeInfos) Reset() {
	*x = LeaseWithEdgeInfos{}
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseWithEdgeInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseWithEdgeInfos) ProtoMessage() {}

func (x *LeaseWithEdgeInfos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseWithEdgeInfos.ProtoReflect.Descriptor instead.
func (*LeaseWithEdgeInfos) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescGZIP(), []int{2}
}

func (x *LeaseWithEdgeInfos) GetLease() *IppoolLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *LeaseWithEdgeInfos) GetLeaseEdgeInfos() *LeaseEdgeInfos {
	if x != nil {
		return x.LeaseEdgeInfos
	}
	return nil
}

type LeasesInfos struct {
	state                protoimpl.MessageState         `protogen:"open.v1"`
	IsRequest            bool                           `protobuf:"varint,1,opt,name=is_request,json=isRequest,proto3" json:"is_request,omitempty"`
	CommunityName        string                         `protobuf:"bytes,2,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	LeasesWithEdgesInfos map[string]*LeaseWithEdgeInfos `protobuf:"bytes,3,rep,name=leases_with_edges_infos,json=leasesWithEdgesInfos,proto3" json:"leases_with_edges_infos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LeasesInfos) Reset() {
	*x = LeasesInfos{}
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeasesInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeasesInfos) ProtoMessage() {}

func (x *LeasesInfos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeasesInfos.ProtoReflect.Descriptor instead.
func (*LeasesInfos) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescGZIP(), []int{3}
}

func (x *LeasesInfos) GetIsRequest() bool {
	if x != nil {
		return x.IsRequest
	}
	return false
}

func (x *LeasesInfos) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

func (x *LeasesInfos) GetLeasesWithEdgesInfos() map[string]*LeaseWithEdgeInfos {
	if x != nil {
		return x.LeasesWithEdgesInfos
	}
	return nil
}

type OnlineCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReply       bool                   `protobuf:"varint,1,opt,name=is_reply,json=isReply,proto3" json:"is_reply,omitempty"`
	Cookie        string                 `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineCheck) Reset() {
	*x = OnlineCheck{}
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCheck) ProtoMessage() {}

func (x *OnlineCheck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCheck.ProtoReflect.Descriptor instead.
func (*OnlineCheck) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineCheck) GetIsReply() bool {
	if x != nil {
		return x.IsReply
	}
	return false
}

func (x *OnlineCheck) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

var File_pkg_protocol_netstruct_proto_leasesinfos_proto protoreflect.FileDescriptor

const file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDesc = "" +
	"\n" +
	".pkg/protocol/netstruct/proto/leasesinfos.proto\x12\tnetstruct\"\x88\x01\n" +
	"\vIppoolLease\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x1b\n" +
	"\texpiry_ns\x18\x03 \x01(\x03R\bexpiryNs\x12\x16\n" +
	"\x06sticky\x18\x04 \x01(\bR\x06sticky\x12\"\n" +
	"\rlast_renew_ns\x18\x05 \x01(\x03R\vlastRenewNs\"\xa7\x01\n" +
	"\x0eLeaseEdgeInfos\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12#\n" +
	"\ris_registered\x18\x02 \x01(\bR\fisRegistered\x128\n" +
	"\x19time_since_last_update_ns\x18\x03 \x01(\x03R\x15timeSinceLastUpdateNs\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x04 \x01(\fR\tvirtualIp\"\x87\x01\n" +
	"\x12LeaseWithEdgeInfos\x12,\n" +
	"\x05lease\x18\x01 \x01(\v2\x16.netstruct.IppoolLeaseR\x05lease\x12C\n" +
	"\x10lease_edge_infos\x18\x02 \x01(\v2\x19.netstruct.LeaseEdgeInfosR\x0eleaseEdgeInfos\"\xa4\x02\n" +
	"\vLeasesInfos\x12\x1d\n" +
	"\n" +
	"is_request\x18\x01 \x01(\bR\tisRequest\x12%\n" +
	"\x0ecommunity_name\x18\x02 \x01(\tR\rcommunityName\x12g\n" +
	"\x17leases_with_edges_infos\x18\x03 \x03(\v20.netstruct.LeasesInfos.LeasesWithEdgesInfosEntryR\x14leasesWithEdgesInfos\x1af\n" +
	"\x19LeasesWithEdgesInfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.netstruct.LeaseWithEdgeInfosR\x05value:\x028\x01\"@\n" +
	"\vOnlineCheck\x12\x19\n" +
	"\bis_reply\x18\x01 \x01(\bR\aisReply\x12\x16\n" +
	"\x06cookie\x18\x02 \x01(\tR\x06cookieB\"Z n2n-go/pkg/protocol/netstruct/pbb\x06proto3"

var (
	file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescOnce sync.Once
	file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescData []byte
)

func file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescGZIP() []byte {
	file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDesc), len(file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDesc)))
	})
	return file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDescData
}

var file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_protocol_netstruct_proto_leasesinfos_proto_goTypes = []any{
	(*IppoolLease)(nil),        // 0: netstruct.IppoolLease
	(*LeaseEdgeInfos)(nil),     // 1: netstruct.LeaseEdgeInfos
	(*LeaseWithEdgeInfos)(nil), // 2: netstruct.LeaseWithEdgeInfos
	(*LeasesInfos)(nil),        // 3: netstruct.LeasesInfos
	(*OnlineCheck)(nil),        // 4: netstruct.OnlineCheck
	nil,                        // 5: netstruct.LeasesInfos.LeasesWithEdgesInfosEntry
}
var file_pkg_protocol_netstruct_proto_leasesinfos_proto_depIdxs = []int32{
	0, // 0: netstruct.LeaseWithEdgeInfos.lease:type_name -> netstruct.IppoolLease
	1, // 1: netstruct.LeaseWithEdgeInfos.lease_edge_infos:type_name -> netstruct.LeaseEdgeInfos
	5, // 2: netstruct.LeasesInfos.leases_with_edges_infos:type_name -> netstruct.LeasesInfos.LeasesWithEdgesInfosEntry
	2, // 3: netstruct.LeasesInfos.LeasesWithEdgesInfosEntry.value:type_name -> netstruct.LeaseWithEdgeInfos
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_protocol_netstruct_proto_leasesinfos_proto_init() }
func file_pkg_protocol_netstruct_proto_leasesinfos_proto_init() {
	if File_pkg_protocol_netstruct_proto_leasesinfos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDesc), len(file_pkg_protocol_netstruct_proto_leasesinfos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_netstruct_proto_leasesinfos_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_netstruct_proto_leasesinfos_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_netstruct_proto_leasesinfos_proto_msgTypes,
	}.Build()
	File_pkg_protocol_netstruct_proto_leasesinfos_proto = out.File
	file_pkg_protocol_netstruct_proto_leasesinfos_proto_goTypes = nil
	file_pkg_protocol_netstruct_proto_leasesinfos_proto_depIdxs = nil
}
