// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pkg/protocol/netstruct/proto/peer.proto

package netstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对应 Go 中的 PeerListRequest
type PeerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityName string                 `protobuf:"bytes,1,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerListRequest) Reset() {
	*x = PeerListRequest{}
	mi := &file_pkg_protocol_netstruct_proto_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerListRequest) ProtoMessage() {}

func (x *PeerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerListRequest.ProtoReflect.Descriptor instead.
func (*PeerListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_peer_proto_rawDescGZIP(), []int{0}
}

func (x *PeerListRequest) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

// 对应 Go 中的 PeerToPing
type PeerToPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckId       string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	IsPong        bool                   `protobuf:"varint,2,opt,name=is_pong,json=isPong,proto3" json:"is_pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerToPing) Reset() {
	*x = PeerToPing{}
	mi := &file_pkg_protocol_netstruct_proto_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerToPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerToPing) ProtoMessage() {}

func (x *PeerToPing) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerToPing.ProtoReflect.Descriptor instead.
func (*PeerToPing) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_peer_proto_rawDescGZIP(), []int{1}
}

func (x *PeerToPing) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *PeerToPing) GetIsPong() bool {
	if x != nil {
		return x.IsPong
	}
	return false
}

var File_pkg_protocol_netstruct_proto_peer_proto protoreflect.FileDescriptor

const file_pkg_protocol_netstruct_proto_peer_proto_rawDesc = "" +
	"\n" +
	"'pkg/protocol/netstruct/proto/peer.proto\x12\tnetstruct\"8\n" +
	"\x0fPeerListRequest\x12%\n" +
	"\x0ecommunity_name\x18\x01 \x01(\tR\rcommunityName\"@\n" +
	"\n" +
	"PeerToPing\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12\x17\n" +
	"\ais_pong\x18\x02 \x01(\bR\x06isPongB\"Z n2n-go/pkg/protocol/netstruct/pbb\x06proto3"

var (
	file_pkg_protocol_netstruct_proto_peer_proto_rawDescOnce sync.Once
	file_pkg_protocol_netstruct_proto_peer_proto_rawDescData []byte
)

func file_pkg_protocol_netstruct_proto_peer_proto_rawDescGZIP() []byte {
	file_pkg_protocol_netstruct_proto_peer_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_netstruct_proto_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_netstruct_proto_peer_proto_rawDesc), len(file_pkg_protocol_netstruct_proto_peer_proto_rawDesc)))
	})
	return file_pkg_protocol_netstruct_proto_peer_proto_rawDescData
}

var file_pkg_protocol_netstruct_proto_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protocol_netstruct_proto_peer_proto_goTypes = []any{
	(*PeerListRequest)(nil), // 0: netstruct.PeerListRequest
	(*PeerToPing)(nil),      // 1: netstruct.PeerToPing
}
var file_pkg_protocol_netstruct_proto_peer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protocol_netstruct_proto_peer_proto_init() }
func file_pkg_protocol_netstruct_proto_peer_proto_init() {
	if File_pkg_protocol_netstruct_proto_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_netstruct_proto_peer_proto_rawDesc), len(file_pkg_protocol_netstruct_proto_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_netstruct_proto_peer_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_netstruct_proto_peer_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_netstruct_proto_peer_proto_msgTypes,
	}.Build()
	File_pkg_protocol_netstruct_proto_peer_proto = out.File
	file_pkg_protocol_netstruct_proto_peer_proto_goTypes = nil
	file_pkg_protocol_netstruct_proto_peer_proto_depIdxs = nil
}
