// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pkg/protocol/netstruct/proto/register.proto

package netstruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对应 Go 中的 SNPublicSecret
type SnPublicSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRequest     bool                   `protobuf:"varint,1,opt,name=is_request,json=isRequest,proto3" json:"is_request,omitempty"`
	PemData       []byte                 `protobuf:"bytes,2,opt,name=pem_data,json=pemData,proto3" json:"pem_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnPublicSecret) Reset() {
	*x = SnPublicSecret{}
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnPublicSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnPublicSecret) ProtoMessage() {}

func (x *SnPublicSecret) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnPublicSecret.ProtoReflect.Descriptor instead.
func (*SnPublicSecret) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_register_proto_rawDescGZIP(), []int{0}
}

func (x *SnPublicSecret) GetIsRequest() bool {
	if x != nil {
		return x.IsRequest
	}
	return false
}

func (x *SnPublicSecret) GetPemData() []byte {
	if x != nil {
		return x.PemData
	}
	return nil
}

// 对应 Go 中的 RegisterRequest
type RegisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EdgeMacAddr        string                 `protobuf:"bytes,1,opt,name=edge_mac_addr,json=edgeMacAddr,proto3" json:"edge_mac_addr,omitempty"`
	EdgeDesc           string                 `protobuf:"bytes,2,opt,name=edge_desc,json=edgeDesc,proto3" json:"edge_desc,omitempty"`
	CommunityName      string                 `protobuf:"bytes,3,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	EncryptedMachineId []byte                 `protobuf:"bytes,4,opt,name=encrypted_machine_id,json=encryptedMachineId,proto3" json:"encrypted_machine_id,omitempty"`
	ClearMachineId     []byte                 `protobuf:"bytes,5,opt,name=clear_machine_id,json=clearMachineId,proto3" json:"clear_machine_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_register_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetEdgeMacAddr() string {
	if x != nil {
		return x.EdgeMacAddr
	}
	return ""
}

func (x *RegisterRequest) GetEdgeDesc() string {
	if x != nil {
		return x.EdgeDesc
	}
	return ""
}

func (x *RegisterRequest) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

func (x *RegisterRequest) GetEncryptedMachineId() []byte {
	if x != nil {
		return x.EncryptedMachineId
	}
	return nil
}

func (x *RegisterRequest) GetClearMachineId() []byte {
	if x != nil {
		return x.ClearMachineId
	}
	return nil
}

// 对应 Go 中的 RetryRegisterRequest
type RetryRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryRegisterRequest) Reset() {
	*x = RetryRegisterRequest{}
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRegisterRequest) ProtoMessage() {}

func (x *RetryRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRegisterRequest.ProtoReflect.Descriptor instead.
func (*RetryRegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_register_proto_rawDescGZIP(), []int{2}
}

// 对应 Go 中的 RegisterResponse
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRegisterOk  bool                   `protobuf:"varint,1,opt,name=is_register_ok,json=isRegisterOk,proto3" json:"is_register_ok,omitempty"`
	VirtualIp     string                 `protobuf:"bytes,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	Masklen       int32                  `protobuf:"varint,3,opt,name=masklen,proto3" json:"masklen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_register_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetIsRegisterOk() bool {
	if x != nil {
		return x.IsRegisterOk
	}
	return false
}

func (x *RegisterResponse) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *RegisterResponse) GetMasklen() int32 {
	if x != nil {
		return x.Masklen
	}
	return 0
}

// 对应 Go 中的 HeartbeatPulse
type HeartbeatPulse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EdgeMacAddr        string                 `protobuf:"bytes,1,opt,name=edge_mac_addr,json=edgeMacAddr,proto3" json:"edge_mac_addr,omitempty"`
	CommunityName      string                 `protobuf:"bytes,2,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	EncryptedMachineId []byte                 `protobuf:"bytes,3,opt,name=encrypted_machine_id,json=encryptedMachineId,proto3" json:"encrypted_machine_id,omitempty"`
	ClearMachineId     []byte                 `protobuf:"bytes,4,opt,name=clear_machine_id,json=clearMachineId,proto3" json:"clear_machine_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatPulse) Reset() {
	*x = HeartbeatPulse{}
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPulse) ProtoMessage() {}

func (x *HeartbeatPulse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPulse.ProtoReflect.Descriptor instead.
func (*HeartbeatPulse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_register_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatPulse) GetEdgeMacAddr() string {
	if x != nil {
		return x.EdgeMacAddr
	}
	return ""
}

func (x *HeartbeatPulse) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

func (x *HeartbeatPulse) GetEncryptedMachineId() []byte {
	if x != nil {
		return x.EncryptedMachineId
	}
	return nil
}

func (x *HeartbeatPulse) GetClearMachineId() []byte {
	if x != nil {
		return x.ClearMachineId
	}
	return nil
}

// 对应 Go 中的 UnregisterRequest
type UnregisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EdgeMacAddr        string                 `protobuf:"bytes,1,opt,name=edge_mac_addr,json=edgeMacAddr,proto3" json:"edge_mac_addr,omitempty"`
	CommunityName      string                 `protobuf:"bytes,2,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	EncryptedMachineId []byte                 `protobuf:"bytes,3,opt,name=encrypted_machine_id,json=encryptedMachineId,proto3" json:"encrypted_machine_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_netstruct_proto_register_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_netstruct_proto_register_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterRequest) GetEdgeMacAddr() string {
	if x != nil {
		return x.EdgeMacAddr
	}
	return ""
}

func (x *UnregisterRequest) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

func (x *UnregisterRequest) GetEncryptedMachineId() []byte {
	if x != nil {
		return x.EncryptedMachineId
	}
	return nil
}

var File_pkg_protocol_netstruct_proto_register_proto protoreflect.FileDescriptor

const file_pkg_protocol_netstruct_proto_register_proto_rawDesc = "" +
	"\n" +
	"+pkg/protocol/netstruct/proto/register.proto\x12\tnetstruct\"J\n" +
	"\x0eSnPublicSecret\x12\x1d\n" +
	"\n" +
	"is_request\x18\x01 \x01(\bR\tisRequest\x12\x19\n" +
	"\bpem_data\x18\x02 \x01(\fR\apemData\"\xd5\x01\n" +
	"\x0fRegisterRequest\x12\"\n" +
	"\redge_mac_addr\x18\x01 \x01(\tR\vedgeMacAddr\x12\x1b\n" +
	"\tedge_desc\x18\x02 \x01(\tR\bedgeDesc\x12%\n" +
	"\x0ecommunity_name\x18\x03 \x01(\tR\rcommunityName\x120\n" +
	"\x14encrypted_machine_id\x18\x04 \x01(\fR\x12encryptedMachineId\x12(\n" +
	"\x10clear_machine_id\x18\x05 \x01(\fR\x0eclearMachineId\"\x16\n" +
	"\x14RetryRegisterRequest\"q\n" +
	"\x10RegisterResponse\x12$\n" +
	"\x0eis_register_ok\x18\x01 \x01(\bR\fisRegisterOk\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\tR\tvirtualIp\x12\x18\n" +
	"\amasklen\x18\x03 \x01(\x05R\amasklen\"\xb7\x01\n" +
	"\x0eHeartbeatPulse\x12\"\n" +
	"\redge_mac_addr\x18\x01 \x01(\tR\vedgeMacAddr\x12%\n" +
	"\x0ecommunity_name\x18\x02 \x01(\tR\rcommunityName\x120\n" +
	"\x14encrypted_machine_id\x18\x03 \x01(\fR\x12encryptedMachineId\x12(\n" +
	"\x10clear_machine_id\x18\x04 \x01(\fR\x0eclearMachineId\"\x90\x01\n" +
	"\x11UnregisterRequest\x12\"\n" +
	"\redge_mac_addr\x18\x01 \x01(\tR\vedgeMacAddr\x12%\n" +
	"\x0ecommunity_name\x18\x02 \x01(\tR\rcommunityName\x120\n" +
	"\x14encrypted_machine_id\x18\x03 \x01(\fR\x12encryptedMachineIdB\"Z n2n-go/pkg/protocol/netstruct/pbb\x06proto3"

var (
	file_pkg_protocol_netstruct_proto_register_proto_rawDescOnce sync.Once
	file_pkg_protocol_netstruct_proto_register_proto_rawDescData []byte
)

func file_pkg_protocol_netstruct_proto_register_proto_rawDescGZIP() []byte {
	file_pkg_protocol_netstruct_proto_register_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_netstruct_proto_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_netstruct_proto_register_proto_rawDesc), len(file_pkg_protocol_netstruct_proto_register_proto_rawDesc)))
	})
	return file_pkg_protocol_netstruct_proto_register_proto_rawDescData
}

var file_pkg_protocol_netstruct_proto_register_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_protocol_netstruct_proto_register_proto_goTypes = []any{
	(*SnPublicSecret)(nil),       // 0: netstruct.SnPublicSecret
	(*RegisterRequest)(nil),      // 1: netstruct.RegisterRequest
	(*RetryRegisterRequest)(nil), // 2: netstruct.RetryRegisterRequest
	(*RegisterResponse)(nil),     // 3: netstruct.RegisterResponse
	(*HeartbeatPulse)(nil),       // 4: netstruct.HeartbeatPulse
	(*UnregisterRequest)(nil),    // 5: netstruct.UnregisterRequest
}
var file_pkg_protocol_netstruct_proto_register_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protocol_netstruct_proto_register_proto_init() }
func file_pkg_protocol_netstruct_proto_register_proto_init() {
	if File_pkg_protocol_netstruct_proto_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_netstruct_proto_register_proto_rawDesc), len(file_pkg_protocol_netstruct_proto_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_netstruct_proto_register_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_netstruct_proto_register_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_netstruct_proto_register_proto_msgTypes,
	}.Build()
	File_pkg_protocol_netstruct_proto_register_proto = out.File
	file_pkg_protocol_netstruct_proto_register_proto_goTypes = nil
	file_pkg_protocol_netstruct_proto_register_proto_depIdxs = nil
}
