// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pkg/p2p/proto/p2p.proto

package p2p

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NatHolePunchState: outcome of a hole-punch attempt, as reported by an edge
// to the relay. This closes the feedback loop that previously did not exist:
// without it the relay can only guess, and either broadcasts forever or
// gives up too early.
type NatHolePunchState int32

const (
	// No attempt reported (default / zero value).
	NatHolePunchState_PunchStateNone NatHolePunchState = 0
	// An attempt is in flight; the relay should wait rather than re-broadcast.
	NatHolePunchState_PunchStateInProgress NatHolePunchState = 1
	// The attempt failed after exhausting its retries. The relay should
	// re-broadcast a fresh instruction, applying its own backoff.
	NatHolePunchState_PunchStateFailed NatHolePunchState = 2
	// The punch succeeded and the tunnel is up. The relay must stop
	// broadcasting for this pair until the tunnel drops.
	NatHolePunchState_PunchStateSucceeded NatHolePunchState = 3
)

// Enum value maps for NatHolePunchState.
var (
	NatHolePunchState_name = map[int32]string{
		0: "PunchStateNone",
		1: "PunchStateInProgress",
		2: "PunchStateFailed",
		3: "PunchStateSucceeded",
	}
	NatHolePunchState_value = map[string]int32{
		"PunchStateNone":       0,
		"PunchStateInProgress": 1,
		"PunchStateFailed":     2,
		"PunchStateSucceeded":  3,
	}
)

func (x NatHolePunchState) Enum() *NatHolePunchState {
	p := new(NatHolePunchState)
	*p = x
	return p
}

func (x NatHolePunchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NatHolePunchState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_p2p_proto_p2p_proto_enumTypes[0].Descriptor()
}

func (NatHolePunchState) Type() protoreflect.EnumType {
	return &file_pkg_p2p_proto_p2p_proto_enumTypes[0]
}

func (x NatHolePunchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NatHolePunchState.Descriptor instead.
func (NatHolePunchState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{0}
}

// NatHoleRole: which side initiates the punch
type NatHoleRole int32

const (
	NatHoleRole_DetectRoleSender   NatHoleRole = 0
	NatHoleRole_DetectRoleReceiver NatHoleRole = 1
)

// Enum value maps for NatHoleRole.
var (
	NatHoleRole_name = map[int32]string{
		0: "DetectRoleSender",
		1: "DetectRoleReceiver",
	}
	NatHoleRole_value = map[string]int32{
		"DetectRoleSender":   0,
		"DetectRoleReceiver": 1,
	}
)

func (x NatHoleRole) Enum() *NatHoleRole {
	p := new(NatHoleRole)
	*p = x
	return p
}

func (x NatHoleRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NatHoleRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_p2p_proto_p2p_proto_enumTypes[1].Descriptor()
}

func (NatHoleRole) Type() protoreflect.EnumType {
	return &file_pkg_p2p_proto_p2p_proto_enumTypes[1]
}

func (x NatHoleRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NatHoleRole.Descriptor instead.
func (NatHoleRole) EnumDescriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{1}
}

// 对应 Go 中的 PeerInfo
type PeerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VirtualIp       string                 `protobuf:"bytes,1,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	MacAddr         []byte                 `protobuf:"bytes,2,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	PubSocket       string                 `protobuf:"bytes,3,opt,name=pub_socket,json=pubSocket,proto3" json:"pub_socket,omitempty"`
	Community       string                 `protobuf:"bytes,4,opt,name=community,proto3" json:"community,omitempty"`
	Desc            string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	P2PEndpoint     string                 `protobuf:"bytes,6,opt,name=p2p_endpoint,json=p2pEndpoint,proto3" json:"p2p_endpoint,omitempty"`
	P2PCapabilities []string               `protobuf:"bytes,7,rep,name=p2p_capabilities,json=p2pCapabilities,proto3" json:"p2p_capabilities,omitempty"`
	NatType         string                 `protobuf:"bytes,8,opt,name=nat_type,json=natType,proto3" json:"nat_type,omitempty"`
	LastSeen        uint64                 `protobuf:"varint,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// NatHole instruction for relay-coordinated NAT hole-punching.
	// When set, the receiving edge should act on the instruction to punch
	// through the NAT together with the peer identified by target_mac.
	NatHoleInstruction *NatHoleInstruction `protobuf:"bytes,10,opt,name=nat_hole_instruction,json=natHoleInstruction,proto3" json:"nat_hole_instruction,omitempty"`
	// Observed source address (host:port) that this edge's P2P socket actually
	// receives packets from. Under a NAT that assigns a different port per
	// destination, this differs from the STUN-discovered pub_socket, which is
	// only a point-in-time snapshot and often stale by the time punching runs.
	// The peer that observes us sends this back so we can punch to the
	// verified-reachable address instead of the predicted one.
	ObservedRaddr string `protobuf:"bytes,11,opt,name=observed_raddr,json=observedRaddr,proto3" json:"observed_raddr,omitempty"`
	// NatHolePunchResult reports the outcome of this edge's most recent
	// hole-punch attempt, so the relay can stop re-broadcasting instructions
	// for pairs that already established P2P and immediately re-arm the ones
	// that just failed.
	PunchResult *NatHolePunchResult `protobuf:"bytes,12,opt,name=punch_result,json=punchResult,proto3" json:"punch_result,omitempty"`
	// MAC of the peer this punch_result refers to. Empty means "no attempt
	// in flight", which lets the relay distinguish a fresh report from a
	// stale one.
	PunchResultPeerMac string `protobuf:"bytes,13,opt,name=punch_result_peer_mac,json=punchResultPeerMac,proto3" json:"punch_result_peer_mac,omitempty"`
	// This edge's current P2P status toward the peer named by
	// punch_result_peer_mac, as a P2PCapacity value (0=Unknown,
	// 1=Pending, 2=Available, 3=FullDuplex, 4=Unavailable).
	//
	// The relay needs this to decide whether a recorded punch success still
	// describes a live tunnel. Without it the relay can see that a punch once
	// succeeded but never that it later stopped working, so it must either
	// suppress the pair forever or re-punch a pair that is already healthy.
	// Both failure modes were seen in the field: a 300s instruction loop
	// against an up pair, and vice versa.
	P2PStatus uint32 `protobuf:"varint,15,opt,name=p2p_status,json=p2pStatus,proto3" json:"p2p_status,omitempty"`
	// The peer's LAN addresses (see RegisterRequest.assisted_sockets), carried
	// so the relay can copy them into NatHoleInstruction.sender_assisted_endpoints.
	AssistedSockets []string `protobuf:"bytes,14,rep,name=assisted_sockets,json=assistedSockets,proto3" json:"assisted_sockets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *PeerInfo) GetMacAddr() []byte {
	if x != nil {
		return x.MacAddr
	}
	return nil
}

func (x *PeerInfo) GetPubSocket() string {
	if x != nil {
		return x.PubSocket
	}
	return ""
}

func (x *PeerInfo) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *PeerInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PeerInfo) GetP2PEndpoint() string {
	if x != nil {
		return x.P2PEndpoint
	}
	return ""
}

func (x *PeerInfo) GetP2PCapabilities() []string {
	if x != nil {
		return x.P2PCapabilities
	}
	return nil
}

func (x *PeerInfo) GetNatType() string {
	if x != nil {
		return x.NatType
	}
	return ""
}

func (x *PeerInfo) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PeerInfo) GetNatHoleInstruction() *NatHoleInstruction {
	if x != nil {
		return x.NatHoleInstruction
	}
	return nil
}

func (x *PeerInfo) GetObservedRaddr() string {
	if x != nil {
		return x.ObservedRaddr
	}
	return ""
}

func (x *PeerInfo) GetPunchResult() *NatHolePunchResult {
	if x != nil {
		return x.PunchResult
	}
	return nil
}

func (x *PeerInfo) GetPunchResultPeerMac() string {
	if x != nil {
		return x.PunchResultPeerMac
	}
	return ""
}

func (x *PeerInfo) GetP2PStatus() uint32 {
	if x != nil {
		return x.P2PStatus
	}
	return 0
}

func (x *PeerInfo) GetAssistedSockets() []string {
	if x != nil {
		return x.AssistedSockets
	}
	return nil
}

type NatHolePunchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State NatHolePunchState      `protobuf:"varint,1,opt,name=state,proto3,enum=p2p.NatHolePunchState" json:"state,omitempty"`
	// Number of attempts the edge burned on the current round.
	Attempts uint32 `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	// Human-readable reason, for relay-side logging only.
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// Index into the relay's behaviour ladder that this round actually ran.
	//
	// The relay keeps a per-pair score per ladder rung and needs to know which
	// one to credit or blame (FRP parity: pkg/nathole/controller.go:271
	// HandleReport calls ReportSuccess(m.Mode, m.Behavior) with the behavior
	// the client reports). Reporting it beats having the relay guess from its
	// own last dispatch, which is wrong whenever an instruction was replaced
	// between being sent and the outcome coming back.
	BehaviorIndex uint32 `protobuf:"varint,4,opt,name=behavior_index,json=behaviorIndex,proto3" json:"behavior_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatHolePunchResult) Reset() {
	*x = NatHolePunchResult{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatHolePunchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatHolePunchResult) ProtoMessage() {}

func (x *NatHolePunchResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatHolePunchResult.ProtoReflect.Descriptor instead.
func (*NatHolePunchResult) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *NatHolePunchResult) GetState() NatHolePunchState {
	if x != nil {
		return x.State
	}
	return NatHolePunchState_PunchStateNone
}

func (x *NatHolePunchResult) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *NatHolePunchResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *NatHolePunchResult) GetBehaviorIndex() uint32 {
	if x != nil {
		return x.BehaviorIndex
	}
	return 0
}

// 对应 Go 中的 PeerInfoList
type PeerInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasOrigin     bool                   `protobuf:"varint,1,opt,name=has_origin,json=hasOrigin,proto3" json:"has_origin,omitempty"`
	Origin        *PeerInfo              `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	PeerInfos     []*PeerInfo            `protobuf:"bytes,3,rep,name=peer_infos,json=peerInfos,proto3" json:"peer_infos,omitempty"`
	EventType     uint32                 `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfoList) Reset() {
	*x = PeerInfoList{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoList) ProtoMessage() {}

func (x *PeerInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoList.ProtoReflect.Descriptor instead.
func (*PeerInfoList) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfoList) GetHasOrigin() bool {
	if x != nil {
		return x.HasOrigin
	}
	return false
}

func (x *PeerInfoList) GetOrigin() *PeerInfo {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *PeerInfoList) GetPeerInfos() []*PeerInfo {
	if x != nil {
		return x.PeerInfos
	}
	return nil
}

func (x *PeerInfoList) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

// 对应 Go 中的 PeerP2PInfos
type PeerP2PInfos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *PeerInfo              `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []*PeerInfo            `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerP2PInfos) Reset() {
	*x = PeerP2PInfos{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerP2PInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerP2PInfos) ProtoMessage() {}

func (x *PeerP2PInfos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerP2PInfos.ProtoReflect.Descriptor instead.
func (*PeerP2PInfos) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *PeerP2PInfos) GetFrom() *PeerInfo {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PeerP2PInfos) GetTo() []*PeerInfo {
	if x != nil {
		return x.To
	}
	return nil
}

// 对应 Go 中的 P2PFullState
type P2PFullState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityName string                 `protobuf:"bytes,1,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	IsRequest     bool                   `protobuf:"varint,2,opt,name=is_request,json=isRequest,proto3" json:"is_request,omitempty"`
	// Reachables: map[string]PeerP2PInfos
	Reachables map[string]*PeerP2PInfos `protobuf:"bytes,3,rep,name=reachables,proto3" json:"reachables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// UnReachables: map[string]PeerCachedInfo
	Unreachables  map[string]*PeerCachedInfo `protobuf:"bytes,4,rep,name=unreachables,proto3" json:"unreachables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PFullState) Reset() {
	*x = P2PFullState{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PFullState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PFullState) ProtoMessage() {}

func (x *P2PFullState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PFullState.ProtoReflect.Descriptor instead.
func (*P2PFullState) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *P2PFullState) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

func (x *P2PFullState) GetIsRequest() bool {
	if x != nil {
		return x.IsRequest
	}
	return false
}

func (x *P2PFullState) GetReachables() map[string]*PeerP2PInfos {
	if x != nil {
		return x.Reachables
	}
	return nil
}

func (x *P2PFullState) GetUnreachables() map[string]*PeerCachedInfo {
	if x != nil {
		return x.Unreachables
	}
	return nil
}

// 对应 Go 中的 PeerCachedInfo
type PeerCachedInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Desc      string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	MacAddr   string                 `protobuf:"bytes,2,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	VirtualIp string                 `protobuf:"bytes,3,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	Community string                 `protobuf:"bytes,4,opt,name=community,proto3" json:"community,omitempty"`
	// time.Duration serialized as int64 nanoseconds
	LastUpdateNs  int64 `protobuf:"varint,5,opt,name=last_update_ns,json=lastUpdateNs,proto3" json:"last_update_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCachedInfo) Reset() {
	*x = PeerCachedInfo{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCachedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCachedInfo) ProtoMessage() {}

func (x *PeerCachedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCachedInfo.ProtoReflect.Descriptor instead.
func (*PeerCachedInfo) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{5}
}

func (x *PeerCachedInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PeerCachedInfo) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *PeerCachedInfo) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *PeerCachedInfo) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *PeerCachedInfo) GetLastUpdateNs() int64 {
	if x != nil {
		return x.LastUpdateNs
	}
	return 0
}

// NatHole message: relay server coordinates NAT hole-punching between
// two HardNAT peers. Sent via PeerInfoList to both edges.
type NatHole struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  NatHoleRole            `protobuf:"varint,1,opt,name=role,proto3,enum=p2p.NatHoleRole" json:"role,omitempty"`
	// port range to try (inclusive)
	PortsRangeFrom uint32 `protobuf:"varint,2,opt,name=ports_range_from,json=portsRangeFrom,proto3" json:"ports_range_from,omitempty"`
	PortsRangeTo   uint32 `protobuf:"varint,3,opt,name=ports_range_to,json=portsRangeTo,proto3" json:"ports_range_to,omitempty"`
	// TTL in seconds for the punch packet
	Ttl uint32 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// MAC address of the edge that should send the punch packets
	TargetMac []byte `protobuf:"bytes,5,opt,name=target_mac,json=targetMac,proto3" json:"target_mac,omitempty"`
	// MAC address of the edge that should receive the punch packets
	SenderMac []byte `protobuf:"bytes,6,opt,name=sender_mac,json=senderMac,proto3" json:"sender_mac,omitempty"`
	// P2P endpoint (ip:port) of the sender
	SenderP2PEndpoint string `protobuf:"bytes,7,opt,name=sender_p2p_endpoint,json=senderP2pEndpoint,proto3" json:"sender_p2p_endpoint,omitempty"`
	// pub_socket (ip:port) of the sender
	SenderPubSocket string `protobuf:"bytes,8,opt,name=sender_pub_socket,json=senderPubSocket,proto3" json:"sender_pub_socket,omitempty"`
	// NAT type of the sender
	SenderNatType string `protobuf:"bytes,9,opt,name=sender_nat_type,json=senderNatType,proto3" json:"sender_nat_type,omitempty"`
	// NAT behavior of the sender
	SenderBehavior string `protobuf:"bytes,10,opt,name=sender_behavior,json=senderBehavior,proto3" json:"sender_behavior,omitempty"`
	// Port difference observed by the sender
	PortsDifference int32 `protobuf:"varint,11,opt,name=ports_difference,json=portsDifference,proto3" json:"ports_difference,omitempty"`
	// Whether the sender has regular port changes
	RegularPortsChange bool `protobuf:"varint,12,opt,name=regular_ports_change,json=regularPortsChange,proto3" json:"regular_ports_change,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NatHole) Reset() {
	*x = NatHole{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatHole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatHole) ProtoMessage() {}

func (x *NatHole) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatHole.ProtoReflect.Descriptor instead.
func (*NatHole) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *NatHole) GetRole() NatHoleRole {
	if x != nil {
		return x.Role
	}
	return NatHoleRole_DetectRoleSender
}

func (x *NatHole) GetPortsRangeFrom() uint32 {
	if x != nil {
		return x.PortsRangeFrom
	}
	return 0
}

func (x *NatHole) GetPortsRangeTo() uint32 {
	if x != nil {
		return x.PortsRangeTo
	}
	return 0
}

func (x *NatHole) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *NatHole) GetTargetMac() []byte {
	if x != nil {
		return x.TargetMac
	}
	return nil
}

func (x *NatHole) GetSenderMac() []byte {
	if x != nil {
		return x.SenderMac
	}
	return nil
}

func (x *NatHole) GetSenderP2PEndpoint() string {
	if x != nil {
		return x.SenderP2PEndpoint
	}
	return ""
}

func (x *NatHole) GetSenderPubSocket() string {
	if x != nil {
		return x.SenderPubSocket
	}
	return ""
}

func (x *NatHole) GetSenderNatType() string {
	if x != nil {
		return x.SenderNatType
	}
	return ""
}

func (x *NatHole) GetSenderBehavior() string {
	if x != nil {
		return x.SenderBehavior
	}
	return ""
}

func (x *NatHole) GetPortsDifference() int32 {
	if x != nil {
		return x.PortsDifference
	}
	return 0
}

func (x *NatHole) GetRegularPortsChange() bool {
	if x != nil {
		return x.RegularPortsChange
	}
	return false
}

// NatHole instruction embedded in PeerInfoList for relay-coordinated punching
type NatHoleInstruction struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Role               NatHoleRole            `protobuf:"varint,1,opt,name=role,proto3,enum=p2p.NatHoleRole" json:"role,omitempty"`
	PortsRangeFrom     uint32                 `protobuf:"varint,2,opt,name=ports_range_from,json=portsRangeFrom,proto3" json:"ports_range_from,omitempty"`
	PortsRangeTo       uint32                 `protobuf:"varint,3,opt,name=ports_range_to,json=portsRangeTo,proto3" json:"ports_range_to,omitempty"`
	Ttl                uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	TargetMac          []byte                 `protobuf:"bytes,5,opt,name=target_mac,json=targetMac,proto3" json:"target_mac,omitempty"`
	SenderMac          []byte                 `protobuf:"bytes,6,opt,name=sender_mac,json=senderMac,proto3" json:"sender_mac,omitempty"`
	SenderP2PEndpoint  string                 `protobuf:"bytes,7,opt,name=sender_p2p_endpoint,json=senderP2pEndpoint,proto3" json:"sender_p2p_endpoint,omitempty"`
	SenderPubSocket    string                 `protobuf:"bytes,8,opt,name=sender_pub_socket,json=senderPubSocket,proto3" json:"sender_pub_socket,omitempty"`
	SenderNatType      string                 `protobuf:"bytes,9,opt,name=sender_nat_type,json=senderNatType,proto3" json:"sender_nat_type,omitempty"`
	SenderBehavior     string                 `protobuf:"bytes,10,opt,name=sender_behavior,json=senderBehavior,proto3" json:"sender_behavior,omitempty"`
	PortsDifference    int32                  `protobuf:"varint,11,opt,name=ports_difference,json=portsDifference,proto3" json:"ports_difference,omitempty"`
	RegularPortsChange bool                   `protobuf:"varint,12,opt,name=regular_ports_change,json=regularPortsChange,proto3" json:"regular_ports_change,omitempty"`
	// Coordination mode this instruction was decided under (FRP nathole mode).
	// 0 = EasyNAT-EasyNAT (no port scan), 3 = HardNAT pair (scan a port range).
	Mode uint32 `protobuf:"varint,13,opt,name=mode,proto3" json:"mode,omitempty"`
	// Index into the behaviour ladder (FRP pkg/nathole/analysis.go
	// mode0Behaviors) this instruction was drawn from.
	//
	// Carried explicitly because protobuf3 cannot distinguish an unset uint32
	// ttl from "no ttl at all", and "no ttl at all" is precisely what ladder
	// entries 4 and 5 mean: both roles emit their probe with the socket's
	// normal TTL, so it traverses the full path instead of dying at hop 4.
	BehaviorIndex uint32 `protobuf:"varint,14,opt,name=behavior_index,json=behaviorIndex,proto3" json:"behavior_index,omitempty"`
	// Milliseconds the relay held this instruction back relative to its
	// counterpart. 0 means "use the relay's configured default".
	SendDelayMs uint32 `protobuf:"varint,15,opt,name=send_delay_ms,json=sendDelayMs,proto3" json:"send_delay_ms,omitempty"`
	// The SENDER's LAN addresses, as the receiver will see them.
	//
	// Only the sender acts on these: it tries them before the sender's
	// STUN-reflexive pub_socket, because when both peers share a LAN a direct
	// delivery needs no NAT mapping on either side and cannot be defeated by a
	// router that does not hairpin.
	//
	// FRP parity: pkg/nathole/nathole.go:210-215 -- `detectAddrs =
	// m.AssistedAddrs; detectAddrs = append(detectAddrs, m.CandidateAddrs...)`
	// for the sender, and `detectAddrs = m.CandidateAddrs` for the receiver.
	// The receiver deliberately gets no assisted list: opening a mapping on its
	// own NAT is its job, and addressing a LAN address would do nothing for that.
	SenderAssistedEndpoints []string `protobuf:"bytes,16,rep,name=sender_assisted_endpoints,json=senderAssistedEndpoints,proto3" json:"sender_assisted_endpoints,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NatHoleInstruction) Reset() {
	*x = NatHoleInstruction{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatHoleInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatHoleInstruction) ProtoMessage() {}

func (x *NatHoleInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatHoleInstruction.ProtoReflect.Descriptor instead.
func (*NatHoleInstruction) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{7}
}

func (x *NatHoleInstruction) GetRole() NatHoleRole {
	if x != nil {
		return x.Role
	}
	return NatHoleRole_DetectRoleSender
}

func (x *NatHoleInstruction) GetPortsRangeFrom() uint32 {
	if x != nil {
		return x.PortsRangeFrom
	}
	return 0
}

func (x *NatHoleInstruction) GetPortsRangeTo() uint32 {
	if x != nil {
		return x.PortsRangeTo
	}
	return 0
}

func (x *NatHoleInstruction) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *NatHoleInstruction) GetTargetMac() []byte {
	if x != nil {
		return x.TargetMac
	}
	return nil
}

func (x *NatHoleInstruction) GetSenderMac() []byte {
	if x != nil {
		return x.SenderMac
	}
	return nil
}

func (x *NatHoleInstruction) GetSenderP2PEndpoint() string {
	if x != nil {
		return x.SenderP2PEndpoint
	}
	return ""
}

func (x *NatHoleInstruction) GetSenderPubSocket() string {
	if x != nil {
		return x.SenderPubSocket
	}
	return ""
}

func (x *NatHoleInstruction) GetSenderNatType() string {
	if x != nil {
		return x.SenderNatType
	}
	return ""
}

func (x *NatHoleInstruction) GetSenderBehavior() string {
	if x != nil {
		return x.SenderBehavior
	}
	return ""
}

func (x *NatHoleInstruction) GetPortsDifference() int32 {
	if x != nil {
		return x.PortsDifference
	}
	return 0
}

func (x *NatHoleInstruction) GetRegularPortsChange() bool {
	if x != nil {
		return x.RegularPortsChange
	}
	return false
}

func (x *NatHoleInstruction) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *NatHoleInstruction) GetBehaviorIndex() uint32 {
	if x != nil {
		return x.BehaviorIndex
	}
	return 0
}

func (x *NatHoleInstruction) GetSendDelayMs() uint32 {
	if x != nil {
		return x.SendDelayMs
	}
	return 0
}

func (x *NatHoleInstruction) GetSenderAssistedEndpoints() []string {
	if x != nil {
		return x.SenderAssistedEndpoints
	}
	return nil
}

var File_pkg_p2p_proto_p2p_proto protoreflect.FileDescriptor

const file_pkg_p2p_proto_p2p_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/p2p/proto/p2p.proto\x12\x03p2p\"\xc6\x04\n" +
	"\bPeerInfo\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x01 \x01(\tR\tvirtualIp\x12\x19\n" +
	"\bmac_addr\x18\x02 \x01(\fR\amacAddr\x12\x1d\n" +
	"\n" +
	"pub_socket\x18\x03 \x01(\tR\tpubSocket\x12\x1c\n" +
	"\tcommunity\x18\x04 \x01(\tR\tcommunity\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12!\n" +
	"\fp2p_endpoint\x18\x06 \x01(\tR\vp2pEndpoint\x12)\n" +
	"\x10p2p_capabilities\x18\a \x03(\tR\x0fp2pCapabilities\x12\x19\n" +
	"\bnat_type\x18\b \x01(\tR\anatType\x12\x1b\n" +
	"\tlast_seen\x18\t \x01(\x04R\blastSeen\x12I\n" +
	"\x14nat_hole_instruction\x18\n" +
	" \x01(\v2\x17.p2p.NatHoleInstructionR\x12natHoleInstruction\x12%\n" +
	"\x0eobserved_raddr\x18\v \x01(\tR\robservedRaddr\x12:\n" +
	"\fpunch_result\x18\f \x01(\v2\x17.p2p.NatHolePunchResultR\vpunchResult\x121\n" +
	"\x15punch_result_peer_mac\x18\r \x01(\tR\x12punchResultPeerMac\x12\x1d\n" +
	"\n" +
	"p2p_status\x18\x0f \x01(\rR\tp2pStatus\x12)\n" +
	"\x10assisted_sockets\x18\x0e \x03(\tR\x0fassistedSockets\"\x9d\x01\n" +
	"\x12NatHolePunchResult\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.p2p.NatHolePunchStateR\x05state\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\rR\battempts\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12%\n" +
	"\x0ebehavior_index\x18\x04 \x01(\rR\rbehaviorIndex\"\xa1\x01\n" +
	"\fPeerInfoList\x12\x1d\n" +
	"\n" +
	"has_origin\x18\x01 \x01(\bR\thasOrigin\x12%\n" +
	"\x06origin\x18\x02 \x01(\v2\r.p2p.PeerInfoR\x06origin\x12,\n" +
	"\n" +
	"peer_infos\x18\x03 \x03(\v2\r.p2p.PeerInfoR\tpeerInfos\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\rR\teventType\"P\n" +
	"\fPeerP2PInfos\x12!\n" +
	"\x04from\x18\x01 \x01(\v2\r.p2p.PeerInfoR\x04from\x12\x1d\n" +
	"\x02to\x18\x02 \x03(\v2\r.p2p.PeerInfoR\x02to\"\x88\x03\n" +
	"\fP2PFullState\x12%\n" +
	"\x0ecommunity_name\x18\x01 \x01(\tR\rcommunityName\x12\x1d\n" +
	"\n" +
	"is_request\x18\x02 \x01(\bR\tisRequest\x12A\n" +
	"\n" +
	"reachables\x18\x03 \x03(\v2!.p2p.P2PFullState.ReachablesEntryR\n" +
	"reachables\x12G\n" +
	"\funreachables\x18\x04 \x03(\v2#.p2p.P2PFullState.UnreachablesEntryR\funreachables\x1aP\n" +
	"\x0fReachablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.p2p.PeerP2PInfosR\x05value:\x028\x01\x1aT\n" +
	"\x11UnreachablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.p2p.PeerCachedInfoR\x05value:\x028\x01\"\xa2\x01\n" +
	"\x0ePeerCachedInfo\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x12\x19\n" +
	"\bmac_addr\x18\x02 \x01(\tR\amacAddr\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x03 \x01(\tR\tvirtualIp\x12\x1c\n" +
	"\tcommunity\x18\x04 \x01(\tR\tcommunity\x12$\n" +
	"\x0elast_update_ns\x18\x05 \x01(\x03R\flastUpdateNs\"\xd9\x03\n" +
	"\aNatHole\x12$\n" +
	"\x04role\x18\x01 \x01(\x0e2\x10.p2p.NatHoleRoleR\x04role\x12(\n" +
	"\x10ports_range_from\x18\x02 \x01(\rR\x0eportsRangeFrom\x12$\n" +
	"\x0eports_range_to\x18\x03 \x01(\rR\fportsRangeTo\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x1d\n" +
	"\n" +
	"target_mac\x18\x05 \x01(\fR\ttargetMac\x12\x1d\n" +
	"\n" +
	"sender_mac\x18\x06 \x01(\fR\tsenderMac\x12.\n" +
	"\x13sender_p2p_endpoint\x18\a \x01(\tR\x11senderP2pEndpoint\x12*\n" +
	"\x11sender_pub_socket\x18\b \x01(\tR\x0fsenderPubSocket\x12&\n" +
	"\x0fsender_nat_type\x18\t \x01(\tR\rsenderNatType\x12'\n" +
	"\x0fsender_behavior\x18\n" +
	" \x01(\tR\x0esenderBehavior\x12)\n" +
	"\x10ports_difference\x18\v \x01(\x05R\x0fportsDifference\x120\n" +
	"\x14regular_ports_change\x18\f \x01(\bR\x12regularPortsChange\"\xff\x04\n" +
	"\x12NatHoleInstruction\x12$\n" +
	"\x04role\x18\x01 \x01(\x0e2\x10.p2p.NatHoleRoleR\x04role\x12(\n" +
	"\x10ports_range_from\x18\x02 \x01(\rR\x0eportsRangeFrom\x12$\n" +
	"\x0eports_range_to\x18\x03 \x01(\rR\fportsRangeTo\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x1d\n" +
	"\n" +
	"target_mac\x18\x05 \x01(\fR\ttargetMac\x12\x1d\n" +
	"\n" +
	"sender_mac\x18\x06 \x01(\fR\tsenderMac\x12.\n" +
	"\x13sender_p2p_endpoint\x18\a \x01(\tR\x11senderP2pEndpoint\x12*\n" +
	"\x11sender_pub_socket\x18\b \x01(\tR\x0fsenderPubSocket\x12&\n" +
	"\x0fsender_nat_type\x18\t \x01(\tR\rsenderNatType\x12'\n" +
	"\x0fsender_behavior\x18\n" +
	" \x01(\tR\x0esenderBehavior\x12)\n" +
	"\x10ports_difference\x18\v \x01(\x05R\x0fportsDifference\x120\n" +
	"\x14regular_ports_change\x18\f \x01(\bR\x12regularPortsChange\x12\x12\n" +
	"\x04mode\x18\r \x01(\rR\x04mode\x12%\n" +
	"\x0ebehavior_index\x18\x0e \x01(\rR\rbehaviorIndex\x12\"\n" +
	"\rsend_delay_ms\x18\x0f \x01(\rR\vsendDelayMs\x12:\n" +
	"\x19sender_assisted_endpoints\x18\x10 \x03(\tR\x17senderAssistedEndpoints*p\n" +
	"\x11NatHolePunchState\x12\x12\n" +
	"\x0ePunchStateNone\x10\x00\x12\x18\n" +
	"\x14PunchStateInProgress\x10\x01\x12\x14\n" +
	"\x10PunchStateFailed\x10\x02\x12\x17\n" +
	"\x13PunchStateSucceeded\x10\x03*;\n" +
	"\vNatHoleRole\x12\x14\n" +
	"\x10DetectRoleSender\x10\x00\x12\x16\n" +
	"\x12DetectRoleReceiver\x10\x01B\x10Z\x0en2n-go/pkg/p2pb\x06proto3"

var (
	file_pkg_p2p_proto_p2p_proto_rawDescOnce sync.Once
	file_pkg_p2p_proto_p2p_proto_rawDescData []byte
)

func file_pkg_p2p_proto_p2p_proto_rawDescGZIP() []byte {
	file_pkg_p2p_proto_p2p_proto_rawDescOnce.Do(func() {
		file_pkg_p2p_proto_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_p2p_proto_p2p_proto_rawDesc), len(file_pkg_p2p_proto_p2p_proto_rawDesc)))
	})
	return file_pkg_p2p_proto_p2p_proto_rawDescData
}

var file_pkg_p2p_proto_p2p_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_p2p_proto_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_p2p_proto_p2p_proto_goTypes = []any{
	(NatHolePunchState)(0),     // 0: p2p.NatHolePunchState
	(NatHoleRole)(0),           // 1: p2p.NatHoleRole
	(*PeerInfo)(nil),           // 2: p2p.PeerInfo
	(*NatHolePunchResult)(nil), // 3: p2p.NatHolePunchResult
	(*PeerInfoList)(nil),       // 4: p2p.PeerInfoList
	(*PeerP2PInfos)(nil),       // 5: p2p.PeerP2PInfos
	(*P2PFullState)(nil),       // 6: p2p.P2PFullState
	(*PeerCachedInfo)(nil),     // 7: p2p.PeerCachedInfo
	(*NatHole)(nil),            // 8: p2p.NatHole
	(*NatHoleInstruction)(nil), // 9: p2p.NatHoleInstruction
	nil,                        // 10: p2p.P2PFullState.ReachablesEntry
	nil,                        // 11: p2p.P2PFullState.UnreachablesEntry
}
var file_pkg_p2p_proto_p2p_proto_depIdxs = []int32{
	9,  // 0: p2p.PeerInfo.nat_hole_instruction:type_name -> p2p.NatHoleInstruction
	3,  // 1: p2p.PeerInfo.punch_result:type_name -> p2p.NatHolePunchResult
	0,  // 2: p2p.NatHolePunchResult.state:type_name -> p2p.NatHolePunchState
	2,  // 3: p2p.PeerInfoList.origin:type_name -> p2p.PeerInfo
	2,  // 4: p2p.PeerInfoList.peer_infos:type_name -> p2p.PeerInfo
	2,  // 5: p2p.PeerP2PInfos.from:type_name -> p2p.PeerInfo
	2,  // 6: p2p.PeerP2PInfos.to:type_name -> p2p.PeerInfo
	10, // 7: p2p.P2PFullState.reachables:type_name -> p2p.P2PFullState.ReachablesEntry
	11, // 8: p2p.P2PFullState.unreachables:type_name -> p2p.P2PFullState.UnreachablesEntry
	1,  // 9: p2p.NatHole.role:type_name -> p2p.NatHoleRole
	1,  // 10: p2p.NatHoleInstruction.role:type_name -> p2p.NatHoleRole
	5,  // 11: p2p.P2PFullState.ReachablesEntry.value:type_name -> p2p.PeerP2PInfos
	7,  // 12: p2p.P2PFullState.UnreachablesEntry.value:type_name -> p2p.PeerCachedInfo
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_p2p_proto_p2p_proto_init() }
func file_pkg_p2p_proto_p2p_proto_init() {
	if File_pkg_p2p_proto_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_p2p_proto_p2p_proto_rawDesc), len(file_pkg_p2p_proto_p2p_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_p2p_proto_p2p_proto_goTypes,
		DependencyIndexes: file_pkg_p2p_proto_p2p_proto_depIdxs,
		EnumInfos:         file_pkg_p2p_proto_p2p_proto_enumTypes,
		MessageInfos:      file_pkg_p2p_proto_p2p_proto_msgTypes,
	}.Build()
	File_pkg_p2p_proto_p2p_proto = out.File
	file_pkg_p2p_proto_p2p_proto_goTypes = nil
	file_pkg_p2p_proto_p2p_proto_depIdxs = nil
}
