// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pkg/p2p/proto/p2p.proto

package p2p

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对应 Go 中的 PeerInfo
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VirtualIp     string                 `protobuf:"bytes,1,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	MacAddr       []byte                 `protobuf:"bytes,2,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	PubSocket     string                 `protobuf:"bytes,3,opt,name=pub_socket,json=pubSocket,proto3" json:"pub_socket,omitempty"`
	Community     string                 `protobuf:"bytes,4,opt,name=community,proto3" json:"community,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *PeerInfo) GetMacAddr() []byte {
	if x != nil {
		return x.MacAddr
	}
	return nil
}

func (x *PeerInfo) GetPubSocket() string {
	if x != nil {
		return x.PubSocket
	}
	return ""
}

func (x *PeerInfo) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *PeerInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// 对应 Go 中的 PeerInfoList
type PeerInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasOrigin     bool                   `protobuf:"varint,1,opt,name=has_origin,json=hasOrigin,proto3" json:"has_origin,omitempty"`
	Origin        *PeerInfo              `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	PeerInfos     []*PeerInfo            `protobuf:"bytes,3,rep,name=peer_infos,json=peerInfos,proto3" json:"peer_infos,omitempty"`
	EventType     uint32                 `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfoList) Reset() {
	*x = PeerInfoList{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoList) ProtoMessage() {}

func (x *PeerInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoList.ProtoReflect.Descriptor instead.
func (*PeerInfoList) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *PeerInfoList) GetHasOrigin() bool {
	if x != nil {
		return x.HasOrigin
	}
	return false
}

func (x *PeerInfoList) GetOrigin() *PeerInfo {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *PeerInfoList) GetPeerInfos() []*PeerInfo {
	if x != nil {
		return x.PeerInfos
	}
	return nil
}

func (x *PeerInfoList) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

// 对应 Go 中的 PeerP2PInfos
type PeerP2PInfos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *PeerInfo              `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []*PeerInfo            `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerP2PInfos) Reset() {
	*x = PeerP2PInfos{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerP2PInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerP2PInfos) ProtoMessage() {}

func (x *PeerP2PInfos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerP2PInfos.ProtoReflect.Descriptor instead.
func (*PeerP2PInfos) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *PeerP2PInfos) GetFrom() *PeerInfo {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *PeerP2PInfos) GetTo() []*PeerInfo {
	if x != nil {
		return x.To
	}
	return nil
}

// 对应 Go 中的 P2PFullState
type P2PFullState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityName string                 `protobuf:"bytes,1,opt,name=community_name,json=communityName,proto3" json:"community_name,omitempty"`
	IsRequest     bool                   `protobuf:"varint,2,opt,name=is_request,json=isRequest,proto3" json:"is_request,omitempty"`
	// Reachables: map[string]PeerP2PInfos
	Reachables map[string]*PeerP2PInfos `protobuf:"bytes,3,rep,name=reachables,proto3" json:"reachables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// UnReachables: map[string]PeerCachedInfo
	Unreachables  map[string]*PeerCachedInfo `protobuf:"bytes,4,rep,name=unreachables,proto3" json:"unreachables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PFullState) Reset() {
	*x = P2PFullState{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PFullState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PFullState) ProtoMessage() {}

func (x *P2PFullState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PFullState.ProtoReflect.Descriptor instead.
func (*P2PFullState) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *P2PFullState) GetCommunityName() string {
	if x != nil {
		return x.CommunityName
	}
	return ""
}

func (x *P2PFullState) GetIsRequest() bool {
	if x != nil {
		return x.IsRequest
	}
	return false
}

func (x *P2PFullState) GetReachables() map[string]*PeerP2PInfos {
	if x != nil {
		return x.Reachables
	}
	return nil
}

func (x *P2PFullState) GetUnreachables() map[string]*PeerCachedInfo {
	if x != nil {
		return x.Unreachables
	}
	return nil
}

// 对应 Go 中的 PeerCachedInfo
type PeerCachedInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Desc      string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	MacAddr   string                 `protobuf:"bytes,2,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	VirtualIp string                 `protobuf:"bytes,3,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	Community string                 `protobuf:"bytes,4,opt,name=community,proto3" json:"community,omitempty"`
	// time.Duration serialized as int64 nanoseconds
	LastUpdateNs  int64 `protobuf:"varint,5,opt,name=last_update_ns,json=lastUpdateNs,proto3" json:"last_update_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCachedInfo) Reset() {
	*x = PeerCachedInfo{}
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCachedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCachedInfo) ProtoMessage() {}

func (x *PeerCachedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_p2p_proto_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCachedInfo.ProtoReflect.Descriptor instead.
func (*PeerCachedInfo) Descriptor() ([]byte, []int) {
	return file_pkg_p2p_proto_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *PeerCachedInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PeerCachedInfo) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *PeerCachedInfo) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *PeerCachedInfo) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *PeerCachedInfo) GetLastUpdateNs() int64 {
	if x != nil {
		return x.LastUpdateNs
	}
	return 0
}

var File_pkg_p2p_proto_p2p_proto protoreflect.FileDescriptor

const file_pkg_p2p_proto_p2p_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/p2p/proto/p2p.proto\x12\x03p2p\"\x95\x01\n" +
	"\bPeerInfo\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x01 \x01(\tR\tvirtualIp\x12\x19\n" +
	"\bmac_addr\x18\x02 \x01(\fR\amacAddr\x12\x1d\n" +
	"\n" +
	"pub_socket\x18\x03 \x01(\tR\tpubSocket\x12\x1c\n" +
	"\tcommunity\x18\x04 \x01(\tR\tcommunity\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\"\xa1\x01\n" +
	"\fPeerInfoList\x12\x1d\n" +
	"\n" +
	"has_origin\x18\x01 \x01(\bR\thasOrigin\x12%\n" +
	"\x06origin\x18\x02 \x01(\v2\r.p2p.PeerInfoR\x06origin\x12,\n" +
	"\n" +
	"peer_infos\x18\x03 \x03(\v2\r.p2p.PeerInfoR\tpeerInfos\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\rR\teventType\"P\n" +
	"\fPeerP2PInfos\x12!\n" +
	"\x04from\x18\x01 \x01(\v2\r.p2p.PeerInfoR\x04from\x12\x1d\n" +
	"\x02to\x18\x02 \x03(\v2\r.p2p.PeerInfoR\x02to\"\x88\x03\n" +
	"\fP2PFullState\x12%\n" +
	"\x0ecommunity_name\x18\x01 \x01(\tR\rcommunityName\x12\x1d\n" +
	"\n" +
	"is_request\x18\x02 \x01(\bR\tisRequest\x12A\n" +
	"\n" +
	"reachables\x18\x03 \x03(\v2!.p2p.P2PFullState.ReachablesEntryR\n" +
	"reachables\x12G\n" +
	"\funreachables\x18\x04 \x03(\v2#.p2p.P2PFullState.UnreachablesEntryR\funreachables\x1aP\n" +
	"\x0fReachablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.p2p.PeerP2PInfosR\x05value:\x028\x01\x1aT\n" +
	"\x11UnreachablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.p2p.PeerCachedInfoR\x05value:\x028\x01\"\xa2\x01\n" +
	"\x0ePeerCachedInfo\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x12\x19\n" +
	"\bmac_addr\x18\x02 \x01(\tR\amacAddr\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x03 \x01(\tR\tvirtualIp\x12\x1c\n" +
	"\tcommunity\x18\x04 \x01(\tR\tcommunity\x12$\n" +
	"\x0elast_update_ns\x18\x05 \x01(\x03R\flastUpdateNsB\x13Z\x11n2n-go/pkg/p2p/pbb\x06proto3"

var (
	file_pkg_p2p_proto_p2p_proto_rawDescOnce sync.Once
	file_pkg_p2p_proto_p2p_proto_rawDescData []byte
)

func file_pkg_p2p_proto_p2p_proto_rawDescGZIP() []byte {
	file_pkg_p2p_proto_p2p_proto_rawDescOnce.Do(func() {
		file_pkg_p2p_proto_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_p2p_proto_p2p_proto_rawDesc), len(file_pkg_p2p_proto_p2p_proto_rawDesc)))
	})
	return file_pkg_p2p_proto_p2p_proto_rawDescData
}

var file_pkg_p2p_proto_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_p2p_proto_p2p_proto_goTypes = []any{
	(*PeerInfo)(nil),       // 0: p2p.PeerInfo
	(*PeerInfoList)(nil),   // 1: p2p.PeerInfoList
	(*PeerP2PInfos)(nil),   // 2: p2p.PeerP2PInfos
	(*P2PFullState)(nil),   // 3: p2p.P2PFullState
	(*PeerCachedInfo)(nil), // 4: p2p.PeerCachedInfo
	nil,                    // 5: p2p.P2PFullState.ReachablesEntry
	nil,                    // 6: p2p.P2PFullState.UnreachablesEntry
}
var file_pkg_p2p_proto_p2p_proto_depIdxs = []int32{
	0, // 0: p2p.PeerInfoList.origin:type_name -> p2p.PeerInfo
	0, // 1: p2p.PeerInfoList.peer_infos:type_name -> p2p.PeerInfo
	0, // 2: p2p.PeerP2PInfos.from:type_name -> p2p.PeerInfo
	0, // 3: p2p.PeerP2PInfos.to:type_name -> p2p.PeerInfo
	5, // 4: p2p.P2PFullState.reachables:type_name -> p2p.P2PFullState.ReachablesEntry
	6, // 5: p2p.P2PFullState.unreachables:type_name -> p2p.P2PFullState.UnreachablesEntry
	2, // 6: p2p.P2PFullState.ReachablesEntry.value:type_name -> p2p.PeerP2PInfos
	4, // 7: p2p.P2PFullState.UnreachablesEntry.value:type_name -> p2p.PeerCachedInfo
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_p2p_proto_p2p_proto_init() }
func file_pkg_p2p_proto_p2p_proto_init() {
	if File_pkg_p2p_proto_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_p2p_proto_p2p_proto_rawDesc), len(file_pkg_p2p_proto_p2p_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_p2p_proto_p2p_proto_goTypes,
		DependencyIndexes: file_pkg_p2p_proto_p2p_proto_depIdxs,
		MessageInfos:      file_pkg_p2p_proto_p2p_proto_msgTypes,
	}.Build()
	File_pkg_p2p_proto_p2p_proto = out.File
	file_pkg_p2p_proto_p2p_proto_goTypes = nil
	file_pkg_p2p_proto_p2p_proto_depIdxs = nil
}
